version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - ../foodgram_app/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    image: maxon57/foodgram_backend:v1.0
    restart: always
    volumes:
      - ../foodgram_app/static_value:/app/static/
      - ../foodgram_app/media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram_frontend
    image: maxon57/foodgram_frontend:v1.0
    volumes:
      - ../foodgram_app/frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../foodgram_app/frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../foodgram_app/static_value:/var/www/static/
      - ../foodgram_app/media_value:/var/www/media/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
